export const CREATE_DECK = 'CREATE_DECK'
export const REMOVE_DECK = 'REMOVE_DECK'
export const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK'
export const FLIP_CARD = 'FLIP_CARD'
export const SET_DECKS = 'SET_DECKS'